name: Hello World
on: [push]

jobs:
  test-host:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"

  test-container:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Verify MySQL connection from container
        run: |
          apt-get update && apt-get install -y mysql-client
          mysql --host mysql -uroot -ppassword -e "SHOW DATABASES"
      - name: "demo command"
        run: |
          mysql --host mysql -uroot -ppassword -e "CREATE DATABASE pets; USE pets; CREATE TABLE cats( id INT unsigned NOT NULL AUTO_INCREMENT,name VARCHAR(150) NOT NULL,     
          owner           VARCHAR(150) NOT NULL,                
          birth           DATE NOT NULL,                       
          PRIMARY KEY     (id)                             
          ); SELECT * FROM TABLE cats;"
